name: action
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v
        with:
          node-version: "14.15.x"
      - run: yarn install
      - run: npm test
